  version: '3'

  services:
    postgres-server-master:
      image: bitnami/postgresql:latest
      container_name: pst-server-master
      ports: 
        - 5433:5433
      environment:
        - POSTGRESQL_REPLICATION_MODE=master
        - POSTGRESQL_USERNAME=postgres
        - POSTGRESQL_PASSWORD=pass
        - POSTGRESQL_DATABASE=postgres
        - POSTGRESQL_REPLICATION_USER=postgres
        - POSTGRESQL_REPLICATION_PASSWORD=pass
    
    postgres-server-slave: 
      image: bitnami/postgresql:latest
      container_name: pst-server-slave 
      depends_on: 
        - postgres-server-master
      ports: 
        - 5432:5432
      environment:
        - POSTGRESQL_REPLICATION_MODE=slave
        - POSTGRESQL_USERNAME=postgres
        - POSTGRESQL_DATABASE=postgres
        - POSTGRESQL_MASTER_HOST=postgres-server-master
        - POSTGRESQL_MASTER_PORT_NUMBER=5432
        - POSTGRESQL_REPLICATION_USER=postgres
        - POSTGRESQL_REPLICATION_PASSWORD=pass
        - ALLOW_EMPTY_PASSWORD=yes 

    go:
      container_name: go
      build: .
      ports:
        - "8080:8080"
      depends_on:
        - postgres-server-master
        - postgres-server-slave
      command: ["./main","postgres"]
    